### ISSUE TITLE
Addition Suggestion

### ISSUE THREAD

**Issue by j-romchain** [PRO100KatYT/RovioActivationScript#1]
after some expirimenting I made an equivalent for running it on wine on linux if anyone finds use. perhaps add it?
you have to redirect the request to yourself by adding `"127.0.0.1 	cloud.rovio.com"` to /etc/hosts, and then host a valid response by doing something like running this python3 script/currently oneLiner command:
```
sudo python3 -c '
from http.server import HTTPServer, SimpleHTTPRequestHandler

# Define the desired response
#HTTP/1.1 200 OK
#Content-Type: text/plain
#
#
response = """status=1&msg=valid"""

class Handler(SimpleHTTPRequestHandler):
  def do_GET(self):
    self.send_response(200)
    self.send_header("Content-type", "text/plain")
    self.end_headers()
    self.wfile.write(response.encode())  # Encode response for sending

# Start the server on port 8080 (you can change this if needed)
httpd = HTTPServer(("", 80), Handler)
print("Serving fake response on port 80...")
httpd.serve_forever()
'

```

**Comment by PRO100KatYT** [comment]
Thanks for the message! I’ve added a link to the repository readme beneath the FiddlerScript that redirects here.
