### ISSUE TITLE
Where should I save the script to actually make it work?

### ISSUE THREAD

**Issue by ojkhbvc** [PRO100KatYT/RovioActivationScript#10]
That's all, thanks :)

**Comment by PRO100KatYT** [comment]
In Fiddler select ![image](https://github.com/user-attachments/assets/092c61cc-c3bc-40b7-962d-3db825512a3a), paste the script there and click  ![image](https://github.com/user-attachments/assets/698d05c4-dc0a-481e-868d-efe9368d572c). Make sure it says ![image](https://github.com/user-attachments/assets/15efc7bc-1eaf-4c97-92f9-55036e842290) in the bottom left corner of Fiddler. Then you should be able to activate Bad Piggies on the PC you're on.
