### ISSUE TITLE
This aint working

### ISSUE THREAD

**Issue by MaurinSz** [PRO100KatYT/RovioActivationScript#2]
I did everything, i dont know why this aint workin, prob it got patched or sum but im doing it correctly

**Comment by PRO100KatYT** [comment]
What Bad Piggies version do you have installed? Versions like 1.0.0 might not work with this script. Try installing one of the newer ones.

**Comment by PRO100KatYT** [comment]
Closing this due to no further response. If the issue persists, please reopen this issue.
