### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Blaezy** [PRO100KatYT/RovioActivationScript#3]
I've follow all your instruction and it didn't work. It just saying no server response , help me

**Comment by PRO100KatYT** [comment]
What Bad Piggies version do you have installed?

**Comment by kworpy** [comment]
This one https://bad-piggies.en.uptodown.com/windows

**Comment by PRO100KatYT** [comment]
> I'm using this one and it doesn't work https://bad-piggies.en.uptodown.com/windows

I installed the game from this link and the activation with the script worked:
![image](https://github.com/user-attachments/assets/73c3b9ec-9d89-4117-a2f0-edb6634f9d34)

Make sure that in Fiddler in the bottom left corner it's set to `Capturing`
![image](https://github.com/user-attachments/assets/03876800-f3a1-4b48-9021-cd6f710ba06c)

**Comment by kworpy** [comment]
ty my dumbass didnt know you had to have fiddler open for it to work
