### ISSUE TITLE
Im trying to follow the guide but since im a idiot i cant resolve it.

### ISSUE THREAD

**Issue by megabuster143** [PRO100KatYT/RovioActivationScript#6]
Could you please send me a more detailed guide ? thank you in advance.

**Comment by PRO100KatYT** [comment]
Sorry for late response, here's a more detailed tutorial:

`Step 1: Install and Configure Fiddler Classic`
Download and install Fiddler Classic from the official website.
Run Fiddler. You might see a popup about AppContainer Configuration. If you do, simply click Cancel.

`Step 2: Access the FiddlerScript Section`
In Fiddler, go to the Tools menu and select FiddlerScript. This will open the FiddlerScript editor.

`Step 3: Clear the Script`
In the FiddlerScript editor, you'll likely see a script named "Introduction". Delete this entire script.

`Step 4: Paste the Activation Script`
Paste the activation script you have into the empty FiddlerScript editor. Make sure to replace any placeholders or specific instructions in the script with the correct values.
Save the script by clicking the Save Script button.

`Step 5: Activate Bad Piggies`
Open Bad Piggies.
Enter any code into the activation window. It doesn't matter what you type.
Confirm the activation.

`Step 6: Verify Activation`
Check if the game is fully activated and all levels are unlocked.
If successful, you can now close Fiddler.


If you encounter issues, try restarting your computer and Fiddler.

By following these steps carefully, you should be able to successfully activate your copy of Bad Piggies. If you have any more questions, feel free to ask them.
